export { Beaco } from "./client";
export { BeacoError, type BeacoValidationIssue } from "./error";
export {
  CreateScheduledEventInputSchema,
  CreateSuppressionInputSchema,
  CreateTemplateInputSchema,
  PublishEventInputSchema,
  RecipientSchema,
  UpdateTemplateInputSchema,
} from "./schemas";
export type {
  BeacoOptions,
  CreateScheduledEventInput,
  CreateSuppressionInput,
  CreateTemplateInput,
  Event,
  EventDetail,
  EventListOptions,
  EventPriority,
  EventStatus,
  Notification,
  NotificationChannel,
  NotificationDetail,
  NotificationListOptions,
  NotificationLog,
  NotificationStatus,
  Page,
  PageOptions,
  PublishEventInput,
  Recipient,
  RequestOptions,
  ScheduledEvent,
  ScheduledEventListOptions,
  ScheduledEventStatus,
  Suppression,
  SuppressionListOptions,
  SuppressionReason,
  SuppressionSource,
  Template,
  TemplateListOptions,
  TemplatePreview,
  UpdateTemplateInput,
} from "./types";
