[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "beaco"
version = "0.2.6"
description = "Official Python SDK for Beaco"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "Michael Ogunjimi" }]
dependencies = []

[project.urls]
Homepage = "https://beaco.michaelogunjimi.com"
Documentation = "https://beaco-docs.michaelogunjimi.com/sdk-python"
Repository = "https://github.com/MichaelOgunjimi/notification-system"
Issues = "https://github.com/MichaelOgunjimi/notification-system/issues"

[tool.setuptools.packages.find]
where = ["src"]
