"""initial_tables

Revision ID: 29f6a434b771
Revises: 
Create Date: 2026-03-26 05:04:30.693549
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f6a434b771'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_table('channel_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_table('retry_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('base_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('max_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('jitter_enabled', sa.Boolean(), nullable=False),
    sa.Column('retry_on_timeout', sa.Boolean(), nullable=False),
    sa.Column('retry_on_5xx', sa.Boolean(), nullable=False),
    sa.Column('retry_on_4xx', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_templates_channel', 'templates', ['channel'], unique=False)
    op.create_index('idx_templates_is_active', 'templates', ['is_active'], unique=False)
    op.create_index('idx_templates_name', 'templates', ['name'], unique=False)
    op.create_index('uq_templates_name_channel', 'templates', ['name', 'channel'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='eventpriority'), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'PROCESSING', 'COMPLETED', 'PARTIALLY_FAILED', 'FAILED', name='eventstatus'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_api_key_id', 'events', ['api_key_id'], unique=False)
    op.create_index('idx_events_batch_id', 'events', ['batch_id'], unique=False)
    op.create_index('idx_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('idx_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    op.create_index('uq_events_idempotency', 'events', ['api_key_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'DELIVERED', 'FAILED', 'DEAD_LETTER', 'CANCELLED', name='notificationstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='eventpriority'), nullable=False),
    sa.Column('recipient_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('recipient_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('rendered_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rendered_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_celery_task_id', 'notifications', ['celery_task_id'], unique=False)
    op.create_index('idx_notifications_channel', 'notifications', ['channel'], unique=False)
    op.create_index('idx_notifications_channel_status', 'notifications', ['channel', 'status'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_event_id', 'notifications', ['event_id'], unique=False)
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False)
    op.create_table('dead_letter_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('recipient_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RETRIED', 'DISCARDED', name='deadletterstatus'), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.Column('retried_at', sa.DateTime(), nullable=True),
    sa.Column('discarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_index('idx_dlq_channel', 'dead_letter_messages', ['channel'], unique=False)
    op.create_index('idx_dlq_failed_at', 'dead_letter_messages', ['failed_at'], unique=False)
    op.create_index('idx_dlq_notification_id', 'dead_letter_messages', ['notification_id'], unique=False)
    op.create_index('idx_dlq_status', 'dead_letter_messages', ['status'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('new_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_logs_created_at', 'notification_logs', ['created_at'], unique=False)
    op.create_index('idx_notification_logs_notification_id', 'notification_logs', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_logs_notification_id', table_name='notification_logs')
    op.drop_index('idx_notification_logs_created_at', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('idx_dlq_status', table_name='dead_letter_messages')
    op.drop_index('idx_dlq_notification_id', table_name='dead_letter_messages')
    op.drop_index('idx_dlq_failed_at', table_name='dead_letter_messages')
    op.drop_index('idx_dlq_channel', table_name='dead_letter_messages')
    op.drop_table('dead_letter_messages')
    op.drop_index('idx_notifications_status', table_name='notifications')
    op.drop_index('idx_notifications_event_id', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_channel_status', table_name='notifications')
    op.drop_index('idx_notifications_channel', table_name='notifications')
    op.drop_index('idx_notifications_celery_task_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_events_idempotency', table_name='events', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_events_event_type', table_name='events')
    op.drop_index('idx_events_created_at', table_name='events')
    op.drop_index('idx_events_batch_id', table_name='events')
    op.drop_index('idx_events_api_key_id', table_name='events')
    op.drop_table('events')
    op.drop_index('uq_templates_name_channel', table_name='templates', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_templates_name', table_name='templates')
    op.drop_index('idx_templates_is_active', table_name='templates')
    op.drop_index('idx_templates_channel', table_name='templates')
    op.drop_table('templates')
    op.drop_table('retry_policies')
    op.drop_table('channel_configs')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
